name: generate-package-list
on: 
  workflow_dispatch:
    inputs:
      minorRelease:
        description: 'Minor release (e.g. 1.13.x)'
        required: true
        type: string
      branchOrTagName:
        description: 'Patch release (e.g. 1.13.2)'
        required: true
        type: string
jobs:
  generate-package-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs site
        uses: actions/checkout@v3
        with:
          path: bottlerocket-project-website
      - name: Checkout bottlerocket os
        uses: actions/checkout@v3
        with:
          repository: bottlerocket-os/bottlerocket
          path: bottlerocket
          ref: v${{ inputs.branchOrTagName }}
      - name: Install prerequisite packages via apt
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt -y install rpm make
      - name: Remove old package list
        run: |
          rm -rf bottlerocket-project-website/content/en/os/$MINOR_RELEASE/version-information/packages/$PATCH_RELEASE/
          find bottlerocket-project-website/content/en/os/$MINOR_RELEASE/version-information/packages/
      - name: Generate package version list
        run: |
          bash bottlerocket-project-website/scripts/software-versions-inventory/software-versions-inventory.sh bottlerocket/ > bottlerocket-project-website/content/en/os/$MINOR_RELEASE/version-information/packages/$PATCH_RELEASE/index.markdown
          cat bottlerocket-project-website/content/en/os/$MINOR_RELEASE/version-information/packages/$PATCH_RELEASE/index.markdown
        env:
          MINOR_RELEASE: ${{ inputs.minorRelease }}
          PATCH_RELEASE: ${{ inputs.branchOrTagName }}
      - name: Check package list
        run: |
          cat bottlerocket-project-website/content/en/os/$MINOR_RELEASE/version-information/packages/$PATCH_RELEASE/index.markdown
        env:
          MINOR_RELEASE: ${{ inputs.minorRelease }}
          PATCH_RELEASE: ${{ inputs.branchOrTagName }}
