name: generate-package-list
on: 
  workflow_dispatch:
    inputs:
      branchOrTagName:
        description: 'Branch or Tag Name'
        required: true
        type: string
jobs:
  generate-package-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs site
        uses: actions/checkout@v3
        with:
          path: bottlerocket-project-website
      - name: Checkout bottlerocket os
        uses: actions/checkout@v3
        with:
          repository: bottlerocket-os/bottlerocket
          path: bottlerocket
      - run: |
          pwd
          ls
          mkdir test-1-2-3
          ls
          echo "testing 1 2 3"
          echo "tag: $BRANCH_TAG_NAME"
          cd bottlerocket
          git tag -l
        env:
          BRANCH_TAG_NAME: ${{ inputs.branchOrTagName }}
